project:
  type: website
  output-dir: docs

website:
  title: "Menu"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Songs
        menu:
          - href: Wild_Mountain_Thyme.qmd
            text: Wild Mountain Thyme
          - href: Leaving_of_Liverpool.qmd
            text: Leaving of Liverpool
          - href: The_Galway_Girl.qmd
            text: The Galway Girl
          - href: All_for_Me_Grog.qmd
            text: All For Me Grog
          - href: The_Black_Velvet_Band.qmd
            text: The Black Velvet Band
          - href: Dirty_Old_Town.qmd
            text: Dirty Old Town
          - href: Gone.qmd
            text: Gone
          - href: Run_Runaway.qmd
            text: Run Runaway
          - href: The_Parting_Glass.qmd
            text: The Parting Glass

format:
  html:
    theme: cosmo
    toc: true
