---
title: "All for Me Grog"
author: "Traditional Seafaring Song"
---

I'm sick in my head 
and I haven't been to bed 
since I first came ashore with me plunder 
I've seen centipedes and snakes 
and me head is full of aches 
and I have to take a path for way out younder

* It's all from me grog
me jolly jolly grog
It's all for me beer and tobacco
For I spent all me tin
with the lassies drinkin' gin
far across the western ocean 
I must wander

Where are me boots, me noggin' noggin' boots? 
They're all sold for beer and tobacco. 
For the heels they are all worn 
and the toes are kicked about 
and the soles are looking out for better weather.

*

Where is me shirt 
my noggin' noggin' shirt? 
It's all sold for beer and tobacco.
For the collar is worn 
and the sleeves they are all torn 
and the tail is looking out for better weather.

*

I'm sick in the head 
and I haven't been to bed, 
Since I first came ashore from me slumber. 
For I spent all me dough 
on the lassies don't you know, 
Far across the western ocean I must wander.

*
