---
title: "The Black Velvet Band"
author: "Traditional Irish"
---

In a neat little town they call Belfast\
Apprentice to a trade I was bound\
And many's an hour's sweet happiness\
Have I spent in this neat little town.\
A sad misfortune came over me\
Which caused me to stray from the land\
Far away from my friends and relations\
Betrayed by the black velvet band.

**Her eyes they shone like diamonds\
you'd think she was the queen of the land\
And her hair hung over her shoulders\
Tied up with a black velvet band.**

I was out strolling on ev 'ning\
not meaning to go very far\
When I met with a pretty you damsel\
who was selling her trade in the bar\
When I watched, she took from a  customer 
and slipped it right into my hand\
then the Watch came and put me in prison\
bad luck to the black velvet band\
.

**Her eyes they shone like diamonds\
you'd think she was the queen of the land\
And her hair hung over her shoulders\
Tied up with a black velvet band.**

I took a stroll with this pretty fair maid\
And the gentleman passing us by\
Well I knew she meant the doing of him\
By the look in her roguish black eye\
A gold watch she took from his pocket\
And placed it right into my hand\
And the very first thing I said was\
Bad 'cess to the black velvet band.

**Her eyes they shone like diamonds\
I thought her the queen of the land\
And her hair hung over her shoulders\
Tied up with a black velvet band.**

Before the judge and the jury\
Next morning I had to appear\
And the judge he said to me 'Young man\
Your case is proven clear'\
We'll give you seven years penal servitude\
To be spent far away from the land\
Far away from your friends and companions\
Betrayed by the black velvet band.

**Her eyes they shone like diamonds\
I thought her the queen of the land\
And her hair hung over her shoulders\
Tied up with a black velvet band.**
